FROM ghcr.io/rails/devcontainer/images/ruby:4.0.5@sha256:5623e7d5e4c40db70c2dc527381a6e3c4b3f750ed60eee79409a163bc58c259c

# Ensure binding is always 0.0.0.0
# Binds the server to all IP addresses of the container, so it can be accessed from outside the container.
ENV BINDING="0.0.0.0"
